### ISSUE TITLE
TypeError: Unable to get property in getCurrentStep in IE11

### ISSUE THREAD

**Issue by poorgeek** [cfpb/hmda-pilot#389]
Steps to reproduce:

* Go to http://dev.hmda-pilot.ec2.devis.com/ in IE11

Error:
```
TypeError: Unable to get property 'undefined' of undefined or null reference
   at getCurrentStep (http://dev.hmda-pilot.ec2.devis.com/scripts/scripts.ff0f70d7.js:1:28685)
   at Anonymous function (http://dev.hmda-pilot.ec2.devis.com/scripts/scripts.ff0f70d7.js:1:21308)
   at $digest (http://dev.hmda-pilot.ec2.devis.com/scripts/scripts.ff0f70d7.js:4:15614)
   at $apply (http://dev.hmda-pilot.ec2.devis.com/scripts/scripts.ff0f70d7.js:4:17263)
   at f (http://dev.hmda-pilot.ec2.devis.com/scripts/scripts.ff0f70d7.js:3:25272)
   at r (http://dev.hmda-pilot.ec2.devis.com/scripts/scripts.ff0f70d7.js:3:27137)
   at onload (http://dev.hmda-pilot.ec2.devis.com/scripts/scripts.ff0f70d7.js:3:27677)
```

*Note:* This error does not appear to cause any problems for IE11. It is still able to process the submitted file and the error does not show up again on any of the other steps within the workflow.

**Comment by doelleri** [comment]
I have seen this occasionally but not consistently in Firefox 37 when reloading the page.
